name: Create Release

on:
  pull_request:
    branches: [main, master]

jobs:
  auto-merge-release:
    uses: tastyigniter/workflows/.github/workflows/auto-merge-release.yml@main
    with:
      release-branch: master
